# application.yml（与之前 RedisTemplate 配置一致）
spring:
  data:
    redis:
      host: localhost  # Redis 服务器地址
      port: 6379       # Redis 端口
      password:        # Redis 密码（无密码则留空）
      timeout: 10000   # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数
          max-idle: 8    # 连接池最大空闲连接数
          min-idle: 2    # 连接池最小空闲连接数
          max-wait: 10000 # 连接池最大阻塞等待时间（毫秒）